# Generated by Django 2.2 on 2020-06-23 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account_info',
            field=models.ForeignKey(help_text='website login account, (not deals with accountant informations).', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nrc',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='NRC Number'),
        ),
    ]
