# Generated by Django 2.2 on 2020-06-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Your Shop Name', max_length=250)),
                ('description', models.TextField(help_text='Shop Description (max:250 words).')),
                ('keywords', models.CharField(help_text='Keywords seperate with comma, eg(Electric Shop, Myanmar Electric, Shop).', max_length=250)),
                ('logo', models.ImageField(blank=True, help_text='Upload Your Shop Logo.', null=True, upload_to='images/')),
                ('phone', models.CharField(help_text='Enter Phone Number', max_length=50)),
                ('email', models.EmailField(help_text='Enter Email Address', max_length=150)),
                ('address', models.TextField(help_text='Enter Shop Address')),
                ('since', models.DateField(default=2020, help_text='Enter Since Year')),
                ('cpright', models.CharField(help_text='Enter Copyright Text', max_length=200)),
                ('author', models.CharField(help_text='Enter App Developer Name', max_length=150)),
            ],
        ),
    ]
