# Generated by Django 2.2 on 2020-06-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='cpright',
            field=models.CharField(help_text='Enter Copyright Text', max_length=200, verbose_name='Copyright'),
        ),
    ]
