# Generated by Django 2.2 on 2020-06-24 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='item',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='price',
            name='item',
        ),
        migrations.AddField(
            model_name='price',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AlterField(
            model_name='price',
            name='low_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Lowest Price'),
        ),
        migrations.AlterField(
            model_name='price',
            name='normal_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Normal Price'),
        ),
    ]
