# Generated by Django 2.2 on 2020-06-24 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200624_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='main_category',
        ),
        migrations.AddField(
            model_name='product',
            name='category1',
            field=models.ManyToManyField(null=True, to='products.MainCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='category2',
            field=models.ManyToManyField(null=True, to='products.SubCategory'),
        ),
    ]
