# Generated by Django 2.2 on 2020-06-26 04:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200624_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='id',
        ),
        migrations.RemoveField(
            model_name='price',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='id',
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='id',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='product',
        ),
        migrations.AddField(
            model_name='price',
            name='product_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.Product'),
        ),
        migrations.AddField(
            model_name='productimages',
            name='product_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='product_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 10, 37, 12, 207242)),
        ),
    ]
