# Generated by Django 2.2 on 2020-06-26 04:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200626_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='product_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category1',
            field=models.ManyToManyField(to='products.MainCategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category2',
            field=models.ManyToManyField(to='products.SubCategory'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='product_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.Product'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 11, 27, 49, 338226)),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.Product'),
        ),
    ]
